In [135]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [136]:
df = pd.read_csv('ncr_ride_bookings.csv')
df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [137]:
df.describe()

,Avg VTAT,Avg CTAT,Cancelled Rides by Customer,Cancelled Rides by Driver,Incomplete Rides,Booking Value,Ride Distance,Driver Ratings,Customer Rating
count,139500.000000,102000.000000,10500.0,27000.0,9000.0,102000.000000,102000.000000,93000.000000,93000.000000
mean,8.456352,29.149636,1.0,1.0,1.0,508.295912,24.637012,4.230992,4.404584
std,3.773564,8.902577,0.0,0.0,0.0,395.805774,14.002138,0.436871,0.437819
min,2.000000,10.000000,1.0,1.0,1.0,50.000000,1.000000,3.000000,3.000000
25%,5.300000,21.600000,1.0,1.0,1.0,234.000000,12.460000,4.100000,4.200000
50%,8.300000,28.800000,1.0,1.0,1.0,414.000000,23.720000,4.300000,4.500000
75%,11.300000,36.800000,1.0,1.0,1.0,689.000000,36.820000,4.600000,4.800000
max,20.000000,45.000000,1.0,1.0,1.0,4277.000000,50.000000,5.000000,5.000000

In [138]:
df.size

3150000

In [139]:
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,...,NaN,NaN,NaN,NaN,NaN,475.0,40.08,3.7,4.1,Uber Wallet
149996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,NaN,NaN,NaN,NaN,NaN,1093.0,21.31,4.8,5.0,UPI
149997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,NaN,NaN,NaN,NaN,NaN,852.0,15.93,3.9,4.4,Cash
149998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,...,NaN,NaN,NaN,NaN,NaN,333.0,45.54,4.1,3.7,UPI
149999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,...,NaN,NaN,NaN,NaN,NaN,806.0,21.19,4.6,4.9,Credit Card

In [140]:
df = df.dropna(subset=["Ride Distance"]).reset_index(drop=True)

In [141]:
df = df.dropna(subset=["Driver Ratings"]).reset_index(drop=True)

In [142]:
df = df.dropna(subset=["Customer Rating"]).reset_index(drop=True)

In [143]:
df.isna().sum()

Date                                     0
Time                                     0
Booking ID                               0
Booking Status                           0
Customer ID                              0
Vehicle Type                             0
Pickup Location                          0
Drop Location                            0
Avg VTAT                                 0
Avg CTAT                                 0
Cancelled Rides by Customer          93000
Reason for cancelling by Customer    93000
Cancelled Rides by Driver            93000
Driver Cancellation Reason           93000
Incomplete Rides                     93000
Incomplete Rides Reason              93000
Booking Value                            0
Ride Distance                            0
Driver Ratings                           0
Customer Rating                          0
Payment Method                           0
dtype: int64

In [144]:
lr = LabelEncoder()
codeVehicle = lr.fit_transform(df['Vehicle Type'])

In [145]:
np.unique(codeVehicle)

array([0, 1, 2, 3, 4, 5, 6])

In [146]:
df['codeVehicle'] = codeVehicle

In [147]:
import pandas as pd

# Convert Time column to datetime, parsing hours, minutes, seconds
df['Time_dt'] = pd.to_datetime(df['Time'], format='%H:%M:%S', errors='coerce')

In [148]:
df['hour'] = df['Time_dt'].dt.hour

In [149]:
def part_of_day(hour):
    if 5 <= hour < 12:
        return 0  # morning
    elif 12 <= hour < 17:
        return 1  # afternoon
    elif 17 <= hour < 21:
        return 2  # evening
    else:
        return 3  # night

df['part_of_day'] = df['hour'].apply(part_of_day)

In [150]:
codePay = lr.fit_transform(df['Payment Method'])

In [151]:
df['codePay'] = codePay

In [152]:
df

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,codeVehicle,Time_dt,hour,part_of_day,codePay
0,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,627.0,13.58,4.9,4.9,Debit Card,0,1900-01-01 08:56:10,8,0,2
1,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,416.0,34.02,4.6,5.0,UPI,4,1900-01-01 17:17:25,17,2,3
2,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,737.0,48.21,4.1,4.3,UPI,1,1900-01-01 22:08:00,22,3,3
3,2024-02-06,09:44:56,"""CNR4096693""",Completed,"""CID4670564""",Auto,AIIMS,Narsinghpur,5.1,18.1,...,316.0,4.85,4.1,4.6,UPI,0,1900-01-01 09:44:56,9,0,3
4,2024-06-17,15:45:58,"""CNR2002539""",Completed,"""CID6800553""",Go Mini,Vaishali,Punjabi Bagh,7.1,20.4,...,640.0,41.24,4.0,4.1,UPI,2,1900-01-01 15:45:58,15,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92995,2024-11-11,19:34:01,"""CNR6500631""",Completed,"""CID4337371""",Go Mini,MG Road,Ghitorni,10.2,44.4,...,475.0,40.08,3.7,4.1,Uber Wallet,2,1900-01-01 19:34:01,19,2,4
92996,2024-11-24,15:55:09,"""CNR2468611""",Completed,"""CID2325623""",Go Mini,Golf Course Road,Akshardham,5.1,30.8,...,1093.0,21.31,4.8,5.0,UPI,2,1900-01-01 15:55:09,15,1,3
92997,2024-09-18,10:55:15,"""CNR6358306""",Completed,"""CID9925486""",Go Sedan,Satguru Ram Singh Marg,Jor Bagh,2.7,23.4,...,852.0,15.93,3.9,4.4,Cash,3,1900-01-01 10:55:15,10,0,0
92998,2024-10-05,07:53:34,"""CNR3030099""",Completed,"""CID9415487""",Auto,Ghaziabad,Saidulajab,6.9,39.6,...,333.0,45.54,4.1,3.7,UPI,0,1900-01-01 07:53:34,7,0,3
92999,2024-03-10,15:38:03,"""CNR3447390""",Completed,"""CID4108667""",Premier Sedan,Ashok Park Main,Gurgaon Sector 29,3.5,33.7,...,806.0,21.19,4.6,4.9,Credit Card,4,1900-01-01 15:38:03,15,1,1

In [153]:
np.unique(codePay)

array([0, 1, 2, 3, 4])

In [154]:
df = df.reset_index(drop=True)

In [155]:
dfx = df[['codeVehicle', 'Ride Distance','Avg VTAT','Avg CTAT']]
dfx.head()

   codeVehicle  Ride Distance  Avg VTAT  Avg CTAT
0            0          13.58      13.4      25.8
1            4          34.02      13.1      28.5
2            1          48.21       5.3      19.6
3            0           4.85       5.1      18.1
4            2          41.24       7.1      20.4

In [156]:
dfpca = dfx[['Ride Distance','Avg VTAT','Avg CTAT']]

In [157]:
dfpca

       Ride Distance  Avg VTAT  Avg CTAT
0              13.58      13.4      25.8
1              34.02      13.1      28.5
2              48.21       5.3      19.6
3               4.85       5.1      18.1
4              41.24       7.1      20.4
...              ...       ...       ...
92995          40.08      10.2      44.4
92996          21.31       5.1      30.8
92997          15.93       2.7      23.4
92998          45.54       6.9      39.6
92999          21.19       3.5      33.7

[93000 rows x 3 columns]

In [158]:
from sklearn.preprocessing import StandardScaler

In [159]:
sl = StandardScaler()
dfpcas = sl.fit_transform(dfpca)

In [160]:
from sklearn.decomposition import PCA

In [161]:
pca = PCA()
df_pca = pca.fit_transform(dfpcas)

In [162]:
dfs = pd.DataFrame(df_pca)

In [163]:
dfs.head()

          0         1         2
0  0.065735 -0.558298  1.559385
1  1.095942 -0.675566  0.457144
2 -0.002631 -1.323561 -1.737417
3 -2.135294 -0.564523  0.441224
4  0.019548 -1.229717 -1.041648

In [164]:
eigen_values = pca.explained_variance_
eigen_values

array([1.00480043, 0.9990792 , 0.99615263])

In [165]:
variance = pca.explained_variance_ratio_
variance

array([0.33492988, 0.33302282, 0.33204731])

In [166]:
dfs.head()

          0         1         2
0  0.065735 -0.558298  1.559385
1  1.095942 -0.675566  0.457144
2 -0.002631 -1.323561 -1.737417
3 -2.135294 -0.564523  0.441224
4  0.019548 -1.229717 -1.041648

In [173]:
dfs['codeVehicle'] = dfx['codeVehicle']
dfs['time'] = df['part_of_day']

In [174]:
dfs

              0         1         2  codeVehicle  time
0      0.065735 -0.558298  1.559385            0     0
1      1.095942 -0.675566  0.457144            4     2
2     -0.002631 -1.323561 -1.737417            1     3
3     -2.135294 -0.564523  0.441224            0     0
4      0.019548 -1.229717 -1.041648            2     1
...         ...       ...       ...          ...   ...
92995  1.620209  1.098884 -0.406314            2     2
92996 -0.772973  0.436095 -0.404859            2     1
92997 -1.784313 -0.053451 -0.580243            3     0
92998  1.081747  0.726616 -1.306608            0     0
92999 -0.919651  0.866085 -0.701978            4     1

[93000 rows x 5 columns]

In [175]:
dfs_numpy = np.array(dfs)

In [176]:
salary_numpy = np.array(df['Booking Value'])

In [177]:
from sklearn.model_selection import train_test_split

In [178]:
xtrain, xtest, ytrain, ytest = train_test_split(dfs_numpy, salary_numpy, test_size = 0.2)

In [179]:
from sklearn.linear_model import LinearRegression

In [180]:
lr_model = LinearRegression()
model = lr_model.fit(xtrain, ytrain)

In [181]:
model

LinearRegression()

In [182]:
ypred = model.predict(xtest)

In [183]:
from sklearn.metrics import mean_absolute_percentage_error, mean_absolute_error

In [184]:
mape = mean_absolute_percentage_error(ypred, ytest)
print(f'{mape:.2%}')

56.71%

In [185]:
mae = mean_absolute_error(ypred, ytest)
print(f'{mae}')

288.0133261447319